//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessAqAcquisitionService.Aquarius.WebService.AAS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSeriesDescription", Namespace="http://schemas.datacontract.org/2004/07/AquariusDataService")]
    [System.SerializableAttribute()]
    public partial class TimeSeriesDescription : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long AqDataIDField;
        
        private string AqtimeseriestypeField;
        
        private System.DateTime EndTimeField;
        
        private double EndValueField;
        
        private string LabelField;
        
        private System.DateTime LastModifiedField;
        
        private long TotalSamplesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long AqDataID {
            get {
                return this.AqDataIDField;
            }
            set {
                if ((this.AqDataIDField.Equals(value) != true)) {
                    this.AqDataIDField = value;
                    this.RaisePropertyChanged("AqDataID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Aqtimeseriestype {
            get {
                return this.AqtimeseriestypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AqtimeseriestypeField, value) != true)) {
                    this.AqtimeseriestypeField = value;
                    this.RaisePropertyChanged("Aqtimeseriestype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double EndValue {
            get {
                return this.EndValueField;
            }
            set {
                if ((this.EndValueField.Equals(value) != true)) {
                    this.EndValueField = value;
                    this.RaisePropertyChanged("EndValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long TotalSamples {
            get {
                return this.TotalSamplesField;
            }
            set {
                if ((this.TotalSamplesField.Equals(value) != true)) {
                    this.TotalSamplesField = value;
                    this.RaisePropertyChanged("TotalSamples");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppendResult", Namespace="http://schemas.datacontract.org/2004/07/AQAcquisitionService.Dto")]
    [System.SerializableAttribute()]
    public partial class AppendResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AppendTokenField;
        
        private int NumPointsAppendedField;
        
        private string TsIdentifierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AppendToken {
            get {
                return this.AppendTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AppendTokenField, value) != true)) {
                    this.AppendTokenField = value;
                    this.RaisePropertyChanged("AppendToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumPointsAppended {
            get {
                return this.NumPointsAppendedField;
            }
            set {
                if ((this.NumPointsAppendedField.Equals(value) != true)) {
                    this.NumPointsAppendedField = value;
                    this.RaisePropertyChanged("NumPointsAppended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TsIdentifier {
            get {
                return this.TsIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.TsIdentifierField, value) != true)) {
                    this.TsIdentifierField = value;
                    this.RaisePropertyChanged("TsIdentifier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldVisit", Namespace="http://schemas.datacontract.org/2004/07/AQAcquisitionService.Dto")]
    [System.SerializableAttribute()]
    public partial class FieldVisit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private long FieldVisitIDField;
        
        private string HistoryLogField;
        
        private long LocationIDField;
        
        private AccessAqAcquisitionService.Aquarius.WebService.AAS.FieldVisitMeasurement[] MeasurementsField;
        
        private string PartyField;
        
        private string RemarksField;
        
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long FieldVisitID {
            get {
                return this.FieldVisitIDField;
            }
            set {
                if ((this.FieldVisitIDField.Equals(value) != true)) {
                    this.FieldVisitIDField = value;
                    this.RaisePropertyChanged("FieldVisitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string HistoryLog {
            get {
                return this.HistoryLogField;
            }
            set {
                if ((object.ReferenceEquals(this.HistoryLogField, value) != true)) {
                    this.HistoryLogField = value;
                    this.RaisePropertyChanged("HistoryLog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long LocationID {
            get {
                return this.LocationIDField;
            }
            set {
                if ((this.LocationIDField.Equals(value) != true)) {
                    this.LocationIDField = value;
                    this.RaisePropertyChanged("LocationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AccessAqAcquisitionService.Aquarius.WebService.AAS.FieldVisitMeasurement[] Measurements {
            get {
                return this.MeasurementsField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasurementsField, value) != true)) {
                    this.MeasurementsField = value;
                    this.RaisePropertyChanged("Measurements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Party {
            get {
                return this.PartyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyField, value) != true)) {
                    this.PartyField = value;
                    this.RaisePropertyChanged("Party");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldVisitMeasurement", Namespace="http://schemas.datacontract.org/2004/07/AQAcquisitionService.Dto")]
    [System.SerializableAttribute()]
    public partial class FieldVisitMeasurement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> ApprovalLevelIDField;
        
        private long FieldVisitIDField;
        
        private string LaboratoryIdField;
        
        private System.DateTime LastModifiedField;
        
        private string MeasurementDetailsField;
        
        private System.Nullable<System.DateTime> MeasurementEndTimeField;
        
        private long MeasurementIDField;
        
        private System.Nullable<long> MeasurementMediaIdField;
        
        private System.DateTime MeasurementTimeField;
        
        private string MeasurementTypeField;
        
        private string RemarksField;
        
        private AccessAqAcquisitionService.Aquarius.WebService.AAS.FieldVisitResult[] ResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> ApprovalLevelID {
            get {
                return this.ApprovalLevelIDField;
            }
            set {
                if ((this.ApprovalLevelIDField.Equals(value) != true)) {
                    this.ApprovalLevelIDField = value;
                    this.RaisePropertyChanged("ApprovalLevelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long FieldVisitID {
            get {
                return this.FieldVisitIDField;
            }
            set {
                if ((this.FieldVisitIDField.Equals(value) != true)) {
                    this.FieldVisitIDField = value;
                    this.RaisePropertyChanged("FieldVisitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LaboratoryId {
            get {
                return this.LaboratoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LaboratoryIdField, value) != true)) {
                    this.LaboratoryIdField = value;
                    this.RaisePropertyChanged("LaboratoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MeasurementDetails {
            get {
                return this.MeasurementDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasurementDetailsField, value) != true)) {
                    this.MeasurementDetailsField = value;
                    this.RaisePropertyChanged("MeasurementDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> MeasurementEndTime {
            get {
                return this.MeasurementEndTimeField;
            }
            set {
                if ((this.MeasurementEndTimeField.Equals(value) != true)) {
                    this.MeasurementEndTimeField = value;
                    this.RaisePropertyChanged("MeasurementEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MeasurementID {
            get {
                return this.MeasurementIDField;
            }
            set {
                if ((this.MeasurementIDField.Equals(value) != true)) {
                    this.MeasurementIDField = value;
                    this.RaisePropertyChanged("MeasurementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> MeasurementMediaId {
            get {
                return this.MeasurementMediaIdField;
            }
            set {
                if ((this.MeasurementMediaIdField.Equals(value) != true)) {
                    this.MeasurementMediaIdField = value;
                    this.RaisePropertyChanged("MeasurementMediaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime MeasurementTime {
            get {
                return this.MeasurementTimeField;
            }
            set {
                if ((this.MeasurementTimeField.Equals(value) != true)) {
                    this.MeasurementTimeField = value;
                    this.RaisePropertyChanged("MeasurementTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MeasurementType {
            get {
                return this.MeasurementTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasurementTypeField, value) != true)) {
                    this.MeasurementTypeField = value;
                    this.RaisePropertyChanged("MeasurementType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AccessAqAcquisitionService.Aquarius.WebService.AAS.FieldVisitResult[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldVisitResult", Namespace="http://schemas.datacontract.org/2004/07/AQAcquisitionService.Dto")]
    [System.SerializableAttribute()]
    public partial class FieldVisitResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<double> CorrectedResultField;
        
        private System.Nullable<double> CorrectionField;
        
        private System.Nullable<System.DateTime> EndTimeField;
        
        private long MeasurementIDField;
        
        private double ObservedResultField;
        
        private string ParameterIDField;
        
        private System.Nullable<double> PercentUncertaintyField;
        
        private string QualifierField;
        
        private System.Nullable<long> QualityCodeIDField;
        
        private string RemarksField;
        
        private string ResultDetailsField;
        
        private long ResultIDField;
        
        private System.Nullable<int> ResultTypeField;
        
        private System.Nullable<System.DateTime> StartTimeField;
        
        private string UnitIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> CorrectedResult {
            get {
                return this.CorrectedResultField;
            }
            set {
                if ((this.CorrectedResultField.Equals(value) != true)) {
                    this.CorrectedResultField = value;
                    this.RaisePropertyChanged("CorrectedResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> Correction {
            get {
                return this.CorrectionField;
            }
            set {
                if ((this.CorrectionField.Equals(value) != true)) {
                    this.CorrectionField = value;
                    this.RaisePropertyChanged("Correction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long MeasurementID {
            get {
                return this.MeasurementIDField;
            }
            set {
                if ((this.MeasurementIDField.Equals(value) != true)) {
                    this.MeasurementIDField = value;
                    this.RaisePropertyChanged("MeasurementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double ObservedResult {
            get {
                return this.ObservedResultField;
            }
            set {
                if ((this.ObservedResultField.Equals(value) != true)) {
                    this.ObservedResultField = value;
                    this.RaisePropertyChanged("ObservedResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ParameterID {
            get {
                return this.ParameterIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterIDField, value) != true)) {
                    this.ParameterIDField = value;
                    this.RaisePropertyChanged("ParameterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<double> PercentUncertainty {
            get {
                return this.PercentUncertaintyField;
            }
            set {
                if ((this.PercentUncertaintyField.Equals(value) != true)) {
                    this.PercentUncertaintyField = value;
                    this.RaisePropertyChanged("PercentUncertainty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Qualifier {
            get {
                return this.QualifierField;
            }
            set {
                if ((object.ReferenceEquals(this.QualifierField, value) != true)) {
                    this.QualifierField = value;
                    this.RaisePropertyChanged("Qualifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<long> QualityCodeID {
            get {
                return this.QualityCodeIDField;
            }
            set {
                if ((this.QualityCodeIDField.Equals(value) != true)) {
                    this.QualityCodeIDField = value;
                    this.RaisePropertyChanged("QualityCodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ResultDetails {
            get {
                return this.ResultDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDetailsField, value) != true)) {
                    this.ResultDetailsField = value;
                    this.RaisePropertyChanged("ResultDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ResultID {
            get {
                return this.ResultIDField;
            }
            set {
                if ((this.ResultIDField.Equals(value) != true)) {
                    this.ResultIDField = value;
                    this.RaisePropertyChanged("ResultID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UnitID {
            get {
                return this.UnitIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitIDField, value) != true)) {
                    this.UnitIDField = value;
                    this.RaisePropertyChanged("UnitID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationDTO", Namespace="http://schemas.datacontract.org/2004/07/AquariusDataService")]
    [System.SerializableAttribute()]
    public partial class LocationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdentifierField;
        
        private System.Nullable<float> LatitudeField;
        
        private string LocationNameField;
        
        private string LocationPathField;
        
        private string LocationTypeNameField;
        
        private System.Nullable<float> LongitudeField;
        
        private float UtcOffsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> ExtendedAttributesField;
        
        private System.Nullable<long> LocationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LocationPath {
            get {
                return this.LocationPathField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationPathField, value) != true)) {
                    this.LocationPathField = value;
                    this.RaisePropertyChanged("LocationPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LocationTypeName {
            get {
                return this.LocationTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationTypeNameField, value) != true)) {
                    this.LocationTypeNameField = value;
                    this.RaisePropertyChanged("LocationTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float UtcOffset {
            get {
                return this.UtcOffsetField;
            }
            set {
                if ((this.UtcOffsetField.Equals(value) != true)) {
                    this.UtcOffsetField = value;
                    this.RaisePropertyChanged("UtcOffset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Collections.Generic.Dictionary<string, object> ExtendedAttributes {
            get {
                return this.ExtendedAttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedAttributesField, value) != true)) {
                    this.ExtendedAttributesField = value;
                    this.RaisePropertyChanged("ExtendedAttributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<long> LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Aquarius.WebService.AAS.IAQAcquisitionService")]
    public interface IAQAcquisitionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAuthSession/GetAuthToken", ReplyAction="http://tempuri.org/IAQAuthSession/GetAuthTokenResponse")]
        string GetAuthToken(string user, string encodedPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/GetTimeSeriesID", ReplyAction="http://tempuri.org/IAQAcquisitionService/GetTimeSeriesIDResponse")]
        long GetTimeSeriesID(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/GetTimeSeriesID2", ReplyAction="http://tempuri.org/IAQAcquisitionService/GetTimeSeriesID2Response")]
        long GetTimeSeriesID2(string parentLabel, string identifier, string parameterType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/GetTimeSeriesList", ReplyAction="http://tempuri.org/IAQAcquisitionService/GetTimeSeriesListResponse")]
        AccessAqAcquisitionService.Aquarius.WebService.AAS.TimeSeriesDescription[] GetTimeSeriesList(long locationID, string parameterType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/GetTimeSeriesListForLocation", ReplyAction="http://tempuri.org/IAQAcquisitionService/GetTimeSeriesListForLocationResponse")]
        AccessAqAcquisitionService.Aquarius.WebService.AAS.TimeSeriesDescription[] GetTimeSeriesListForLocation(long locationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/GetLocationId", ReplyAction="http://tempuri.org/IAQAcquisitionService/GetLocationIdResponse")]
        long GetLocationId(string locationIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/AppendTimeSeriesFromBytes", ReplyAction="http://tempuri.org/IAQAcquisitionService/AppendTimeSeriesFromBytesResponse")]
        int AppendTimeSeriesFromBytes(long id, byte[] csvbytes, string userName, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/AppendTimeSeriesFromBytes2", ReplyAction="http://tempuri.org/IAQAcquisitionService/AppendTimeSeriesFromBytes2Response")]
        AccessAqAcquisitionService.Aquarius.WebService.AAS.AppendResult AppendTimeSeriesFromBytes2(long id, byte[] csvbytes, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/CreateTimeSeries", ReplyAction="http://tempuri.org/IAQAcquisitionService/CreateTimeSeriesResponse")]
        long CreateTimeSeries(string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/CreateTimeSeries2", ReplyAction="http://tempuri.org/IAQAcquisitionService/CreateTimeSeries2Response")]
        long CreateTimeSeries2(long parentId, string label, string comments, string description, string parameter, int utcOffsetInMinutes, string unit, double maxGaps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/AppendAndMerge", ReplyAction="http://tempuri.org/IAQAcquisitionService/AppendAndMergeResponse")]
        int AppendAndMerge(string SiteName, string comment, string configName, string parameterMap, string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/UndoAppend", ReplyAction="http://tempuri.org/IAQAcquisitionService/UndoAppendResponse")]
        int UndoAppend(string identifier, string appendToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/GetTimeSeries", ReplyAction="http://tempuri.org/IAQAcquisitionService/GetTimeSeriesResponse")]
        string GetTimeSeries(long aqDataId, string viewName, System.DateTime fromTime, System.DateTime toTime, System.DateTime asOfTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/DeleteTimeSeriesPointsByTimeRange", ReplyAction="http://tempuri.org/IAQAcquisitionService/DeleteTimeSeriesPointsByTimeRangeRespons" +
            "e")]
        int DeleteTimeSeriesPointsByTimeRange(long id, System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/DeleteTimeSeries", ReplyAction="http://tempuri.org/IAQAcquisitionService/DeleteTimeSeriesResponse")]
        void DeleteTimeSeries(long timeSeriesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/GetFieldVisitsByLocation", ReplyAction="http://tempuri.org/IAQAcquisitionService/GetFieldVisitsByLocationResponse")]
        AccessAqAcquisitionService.Aquarius.WebService.AAS.FieldVisit[] GetFieldVisitsByLocation(long locationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/GetFieldVisitsByLocationAndDate", ReplyAction="http://tempuri.org/IAQAcquisitionService/GetFieldVisitsByLocationAndDateResponse")]
        AccessAqAcquisitionService.Aquarius.WebService.AAS.FieldVisit[] GetFieldVisitsByLocationAndDate(long locationId, System.DateTime startDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/SaveFieldVisit", ReplyAction="http://tempuri.org/IAQAcquisitionService/SaveFieldVisitResponse")]
        AccessAqAcquisitionService.Aquarius.WebService.AAS.FieldVisit SaveFieldVisit(AccessAqAcquisitionService.Aquarius.WebService.AAS.FieldVisit fv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/GetAllLocations", ReplyAction="http://tempuri.org/IAQAcquisitionService/GetAllLocationsResponse")]
        AccessAqAcquisitionService.Aquarius.WebService.AAS.LocationDTO[] GetAllLocations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/GetLocation", ReplyAction="http://tempuri.org/IAQAcquisitionService/GetLocationResponse")]
        AccessAqAcquisitionService.Aquarius.WebService.AAS.LocationDTO GetLocation(long locationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/CreateLocation", ReplyAction="http://tempuri.org/IAQAcquisitionService/CreateLocationResponse")]
        long CreateLocation(AccessAqAcquisitionService.Aquarius.WebService.AAS.LocationDTO location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/ModifyLocation", ReplyAction="http://tempuri.org/IAQAcquisitionService/ModifyLocationResponse")]
        void ModifyLocation(AccessAqAcquisitionService.Aquarius.WebService.AAS.LocationDTO location);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAQAcquisitionServiceChannel : AccessAqAcquisitionService.Aquarius.WebService.AAS.IAQAcquisitionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AQAcquisitionServiceClient : System.ServiceModel.ClientBase<AccessAqAcquisitionService.Aquarius.WebService.AAS.IAQAcquisitionService>, AccessAqAcquisitionService.Aquarius.WebService.AAS.IAQAcquisitionService {
        
        public AQAcquisitionServiceClient() {
        }
        
        public AQAcquisitionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AQAcquisitionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AQAcquisitionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AQAcquisitionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAuthToken(string user, string encodedPassword) {
            return base.Channel.GetAuthToken(user, encodedPassword);
        }
        
        public long GetTimeSeriesID(string identifier) {
            return base.Channel.GetTimeSeriesID(identifier);
        }
        
        public long GetTimeSeriesID2(string parentLabel, string identifier, string parameterType) {
            return base.Channel.GetTimeSeriesID2(parentLabel, identifier, parameterType);
        }
        
        public AccessAqAcquisitionService.Aquarius.WebService.AAS.TimeSeriesDescription[] GetTimeSeriesList(long locationID, string parameterType) {
            return base.Channel.GetTimeSeriesList(locationID, parameterType);
        }
        
        public AccessAqAcquisitionService.Aquarius.WebService.AAS.TimeSeriesDescription[] GetTimeSeriesListForLocation(long locationID) {
            return base.Channel.GetTimeSeriesListForLocation(locationID);
        }
        
        public long GetLocationId(string locationIdentifier) {
            return base.Channel.GetLocationId(locationIdentifier);
        }
        
        public int AppendTimeSeriesFromBytes(long id, byte[] csvbytes, string userName, string comment) {
            return base.Channel.AppendTimeSeriesFromBytes(id, csvbytes, userName, comment);
        }
        
        public AccessAqAcquisitionService.Aquarius.WebService.AAS.AppendResult AppendTimeSeriesFromBytes2(long id, byte[] csvbytes, string userName) {
            return base.Channel.AppendTimeSeriesFromBytes2(id, csvbytes, userName);
        }
        
        public long CreateTimeSeries(string identifier) {
            return base.Channel.CreateTimeSeries(identifier);
        }
        
        public long CreateTimeSeries2(long parentId, string label, string comments, string description, string parameter, int utcOffsetInMinutes, string unit, double maxGaps) {
            return base.Channel.CreateTimeSeries2(parentId, label, comments, description, parameter, utcOffsetInMinutes, unit, maxGaps);
        }
        
        public int AppendAndMerge(string SiteName, string comment, string configName, string parameterMap, string filePath) {
            return base.Channel.AppendAndMerge(SiteName, comment, configName, parameterMap, filePath);
        }
        
        public int UndoAppend(string identifier, string appendToken) {
            return base.Channel.UndoAppend(identifier, appendToken);
        }
        
        public string GetTimeSeries(long aqDataId, string viewName, System.DateTime fromTime, System.DateTime toTime, System.DateTime asOfTime) {
            return base.Channel.GetTimeSeries(aqDataId, viewName, fromTime, toTime, asOfTime);
        }
        
        public int DeleteTimeSeriesPointsByTimeRange(long id, System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.DeleteTimeSeriesPointsByTimeRange(id, startTime, endTime);
        }
        
        public void DeleteTimeSeries(long timeSeriesId) {
            base.Channel.DeleteTimeSeries(timeSeriesId);
        }
        
        public AccessAqAcquisitionService.Aquarius.WebService.AAS.FieldVisit[] GetFieldVisitsByLocation(long locationId) {
            return base.Channel.GetFieldVisitsByLocation(locationId);
        }
        
        public AccessAqAcquisitionService.Aquarius.WebService.AAS.FieldVisit[] GetFieldVisitsByLocationAndDate(long locationId, System.DateTime startDate) {
            return base.Channel.GetFieldVisitsByLocationAndDate(locationId, startDate);
        }
        
        public AccessAqAcquisitionService.Aquarius.WebService.AAS.FieldVisit SaveFieldVisit(AccessAqAcquisitionService.Aquarius.WebService.AAS.FieldVisit fv) {
            return base.Channel.SaveFieldVisit(fv);
        }
        
        public AccessAqAcquisitionService.Aquarius.WebService.AAS.LocationDTO[] GetAllLocations() {
            return base.Channel.GetAllLocations();
        }
        
        public AccessAqAcquisitionService.Aquarius.WebService.AAS.LocationDTO GetLocation(long locationId) {
            return base.Channel.GetLocation(locationId);
        }
        
        public long CreateLocation(AccessAqAcquisitionService.Aquarius.WebService.AAS.LocationDTO location) {
            return base.Channel.CreateLocation(location);
        }
        
        public void ModifyLocation(AccessAqAcquisitionService.Aquarius.WebService.AAS.LocationDTO location) {
            base.Channel.ModifyLocation(location);
        }
    }
}
